spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/elizkurtulus/library-management-microservices.git
          default-label: master
          search-paths:
            - configurations
            - configurations/{application}
          clone-on-start: true
          force-pull: true
          username: ${GIT_USERNAME:elizkurtulus}
          password: ${GIT_MIC_PASSWORD:password}
server:
  port: 8989